//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posts
    {
        public int PostId { get; set; }
        public int CategoryId { get; set; }
        public int ArchiveId { get; set; }
        public string PostTitle { get; set; }
        public string PostContent { get; set; }
        public System.DateTime PostDateTime { get; set; }
        public string PostPhoto { get; set; }
    
        public virtual Archives Archives { get; set; }
        public virtual Categories Categories { get; set; }
    }
}
